#!/usr/bin/env php
<?php
/**
 * @file
 * Drupal CI's console.
 */

$loader = require_once __DIR__ . '/vendor/autoload.php';
// Sets the socket timeout to a very long time so that
// Guzzle requests to docker have enough time to wait for output.
ini_set("default_socket_timeout", "1000");
use DrupalCI\Console\DrupalCIConsoleApp;

$app = new DrupalCIConsoleApp('DrupalCI - CommandLine', '0.1');
$app->run();
