template_mapper.template_mapping.*:
  type: config_entity
  label: 'Template mapping config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    mapping:
      type: string
      label: 'mapping'
    uuid:
      type: string
